import { User } from "./githubUser"

export let user: User =
{
    "login": "mpampis",
    "id": 3257012,
    "node_id": "MDQ6VXNlcjMyNTcwMTI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3257012?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mpampis",
    "html_url": "https://github.com/mpampis",
    "followers_url": "https://api.github.com/users/mpampis/followers",
    "following_url": "https://api.github.com/users/mpampis/following{/other_user}",
    "gists_url": "https://api.github.com/users/mpampis/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mpampis/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mpampis/subscriptions",
    "organizations_url": "https://api.github.com/users/mpampis/orgs",
    "repos_url": "https://api.github.com/users/mpampis/repos",
    "events_url": "https://api.github.com/users/mpampis/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mpampis/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 3,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2013-01-13T10:33:45Z",
    "updated_at": "2022-01-10T08:41:53Z"
}